const POST_ADD_CATALOGUE = "POST_ADD_KATEGORI";
// GENERAL
const USER = "USER";
const SUCCESS = "SUCCESS";

// AXIOS
const POST = "POST";
const GET = "GET";

// AXIOS LOG TITLE
const GET_CHECK_AUTH_TOKEN = "GET_CHECK_AUTH_TOKEN";
const POST_SEND_PROFILEPIC = "POST_SEND_PROFILEPIC";

// EMAIL TYPE
const SEND_OTP = "SEND_OTP";

// EMAIL SUBJECT
const OTP_EMAIL = "Account Registration - Here is your OTP number";

// API URLs
const CHECK_AUTH_TOKEN = `/v${process.env.APP_OLYMPUS_SERVICE_MAJOR_VERSION}/auth/check`;

module.exports = {
    POST_ADD_CATALOGUE,
    POST_SEND_PROFILEPIC,
    USER,
    SUCCESS,
    POST,
    GET,
    GET_CHECK_AUTH_TOKEN,
    SEND_OTP,
    OTP_EMAIL,
    CHECK_AUTH_TOKEN
}